# About the Author {-}

I am a biologist turned bioinformatician turned data scientist from Münster in Germany. I've earned my PhD from the University of Münster, where I worked on the link between flowering time and immune defense in plants using quantitative genetics and RNA-sequencing. My overarching interest has been evolutionary biology and genetics. Following my PhD, I continued as a Postdoc for two years; during this time, I was working as a bioinformatician for Next-Generation-Sequencing analysis on questions relating to immunology - specifically inflammation, immune tolerance and auto-inflammatory diseases. Since July of 2017 I have switched to industry, where I work as a data scientist for codecentric AG.

I'm a big fan of R and I write [a blog](www.shirin-glander.de) where I explore different data sets and techniques in R. I also teach ballroom and Latin dance courses.

You can find me and my package for gene expression analysis (exprAnalysis) on [Github](https://github.com/ShirinG).


# Why use R for Statistical Genetics?

R[@R-core] provides a big collection of packages geared towards statistical analyses and genetics. It allows you to start with a dataset and answer multiple questions by combining different functions and analyses specific to your area of interest. Moreover, R makes it easy to clean and preprocess data. R is open-source and can be used across platforms, like Windows, Mac OS and Linux. Its powerful visualization tools make it also very convenient for producing publication-ready graphics along with your analyses. The community around R is very active and you can find answers and support on many levels, like [the R help from CRAN](https://www.r-project.org/help.html), on StackOverflow(https://stackoverflow.com/), on [Google Groups](https://groups.google.com/forum/#!forum/r-help-archive) or on [Bioconductor](https://www.bioconductor.org/help/).


# The Basics of R {-}

> "R is an integrated suite of software facilities for data manipulation, calculation and graphical
display." [An Introduction to R - Notes on R: A Programming Environment for Data Analysis and Graphics version 3.4.0 (2017-04-21) by W. N. Venables, D. M. Smith and the R Core Team](https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf)

R[@R-core] has originally been developed for statistical analysis and is a powerful toolbox for a wide range of tasks pertaining to data handling, statistical modeling and visualisation. It consists of a core distribution that contains basic functions. You can use additional packages for specific analyses.

This books assumes a basic knowledge about getting data into R, installing and loading packages, calling functions, etc. It is beyond the scope of this book to provide an in depth introduction to R. Luckily, there are a large number of free online resources available, like

- [An Introduction to R - Notes on R: A Programming Environment for Data Analysis and Graphics version 3.4.0 (2017-04-21) by W. N. Venables, D. M. Smith and the R Core Team](https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf)
- [Data Camp](https://www.datacamp.com/courses/free-introduction-to-r)
- [Penn State Statistics resources](https://onlinecourses.science.psu.edu/statprogram/r)
- ['Introducin R' by Germán Rodríguez from Princeton University](http://data.princeton.edu/R/introducingR.pdf)
- etc.


## Software information and conventions {-}

Package names are written in bold text (e.g., **rmarkdown**), and inline code and filenames are formatted in a typewriter font (e.g., `plot()`). Function names are followed by parentheses (e.g., `bookdown::render_book()`).

Some packages are available via [CRAN](https://cran.r-project.org/)\index{CRAN}, while others are hosted at [Bioconductor](https://www.bioconductor.org/)\index{Bioconductor}. I will provide package installation instructions at the beginning of each section, indicating where each package can be found.
I will also be using the `library()` function, rather than `require()` for loading packages to make sure that we will get an error message in case packages have not been installed correctly.

The example workflows included are meant to illustrate the theoretical concepts and get you started on your own analysis. They are minimal examples of the necessary steps but are not meant to substitute the package manuals. When you want to apply the workflows to your own data, I highly recommend going back to the package documentation to find out about additional functions and using the `help()` function to explore parameter options. I will be using the same naming and code schemes as in the package manuals to make finding the relevant parts easy.

I used the **knitr**\index{knitr} package and the **bookdown**\index{bookdown} package to compile this book. My R session information is shown below:

```{r}
sessionInfo()
```
