--- 
title: "Statistical Genetics: Analyses with R"
author: "Dr. Shirin Glander"
date: '`r Sys.Date()`'
output:
  bookdown::gitbook:
    highlight: tango
  bookdown::pdf_book:
    keep_tex: yes
bibliography:
- book.bib
- packages.bib
description: Description to come...
documentclass: book
fontsize: 12pt
link-citations: yes
lof: yes
lot: yes
monofont: Source Code Pro
monofontoptions: Scale=0.7
colorlinks: yes
site: bookdown::bookdown_site
biblio-style: apalike
---

<<pre_load>>=
options(tikzDefaultEngine='xetex')
@

# Preface {-}

## Why read this book {-}

## Structure of the book {-}

## Software information and conventions {-}

All analyses are run on R version 3.3.3 (2017-03-06) -- "Another Canoe".

Some packages are available via [CRAN](https://cran.r-project.org/), while others are hosted at [Bioconductor](https://www.bioconductor.org/). I will provide package installation instructions at the beginning of each example, indicating where each package can be found.

I will also be using the **library()** function, rather than **require()** for loading packages to make sure that we will get an error message in case packages have not been installed correctly.

The example workflows included are meant to illustrate the theoretical concepts and get you started on your own analysis. They are minimal examples of the necessary steps but are not meant to substitute the package manuals. When you want to apply the workflows to your own data, I highly recommend going back to the package documentation to find out about additional functions and using the help() function to explore parameter options. I will be using the same naming and code schemes as in the package manuals to make finding the relevant parts easy.

## Acknowledgments {-}



